/*
 * This file is dynamically generated by a python script based on AST node documentation from RedBaron.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 *
 * The classes defined here inherit from BoxActor, which is responsible for implementation, and PythonNode, 
 * which is responsible for interfacing with python AST nodes. Edit those classes to add functionality. 
 */

#pragma once

#include "GameFramework/Actor.h"
#include "BoxActor.h"
#include "PythonNode.h"
#include "NodeBox.generated.h"

UCLASS()
class PROCKFPS_API ANodeBox : public ABoxActor, public PythonNode
{
	GENERATED_BODY()
public:	
	ANodeBox(PyObject *native) : PythonNode(native) {}
	ANodeBox() : PythonNode(nullptr) {}


};
